name: Generate Static Site
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install PHP dependencies
        run: |
          if [ -f composer.json ]; then
            composer install
          fi
      - name: Generate static HTML from PHP files
        run: |
          find . -type f -name "*.php" | while read -r php_file; do
            html_file="${php_file%.php}.html"
            php "$php_file" > "$html_file"
            echo "Converted $php_file to $html_file"
          done
      - name: Commit and push to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b gh-pages || git checkout gh-pages
          git add .
          git commit -m "Generate static HTML from PHP files" || echo "No changes to commit"
          git push origin gh-pages